redis:
  host: 212.129.142.221
  port: 6379
  timeout: 5000
  password: my-redis-pass-for-2018
spring:
  application:
    name: api-gateway-server
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  prefix: /api
  sensitive-headers:
  forceOriginalQueryStringEncoding: true
  ignored-services: '*'
  routes:
    user-server: /user/**
  ribbon:
    eager-load:
      enabled: true
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: false
    ConnectTimeout: 10000
    ReadTimeout: 10000
  add-host-header: true
  add-proxy-headers: true
hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 60000
gate:
  ignore:
    authUrl: /user/login,/user/register
