spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://212.129.142.221:3306/my_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.dail.user.model
redis:
  host: 212.129.142.221
  port: 6379
