package com.dail.user.mapper;

import com.dail.user.model.UserToken;
import com.dail.user.model.UserTokenExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    long countByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    int deleteByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    int insert(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    int insertSelective(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    List<UserToken> selectByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    UserToken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserToken record, @Param("example") UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserToken record, @Param("example") UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserToken record);
}
